### ISSUE TITLE
ServusTv plugin question

### ISSUE THREAD

**Issue by someziggyman** [flashdagger/ytdlp-plugins#2]
Hello and thank you so much for your cool plugins. 
I've got a rather newbie and probably stupid question here form an average command line user.

I tried to adapt servusTVplugin for my local machine yt-dlp build.
Downloaded servustv.py, moved it to yt-dlp/extactors, edited extractors.py and the actual servustv.py file a bit to match paths for .common and ..utils, basically made all the edits needed including a couple methods to utils.py...

However, when trying to compile I'm getting this error below:

/usr/bin/env python3 devscripts/make_lazy_extractors.py yt_dlp/extractor/lazy_extractors.py
Traceback (most recent call last):
  File "/yt-dlp/devscripts/make_lazy_extractors.py", line 125, in <module>
    main()
  File "/yt-dlp/devscripts/make_lazy_extractors.py", line 38, in main
    module_src = '\n'.join((
  File "/yt-dlp/devscripts/make_lazy_extractors.py", line 79, in build_ies
    yield build_lazy_ie(ie, ie.__name__, attr_base)
  File "/yt-dlp/devscripts/make_lazy_extractors.py", line 121, in build_lazy_ie
    return s + '\n'.join(extra_ie_code(ie, attr_base))
  File "/yt-dlp/devscripts/make_lazy_extractors.py", line 65, in extra_ie_code
    val = getattr(ie, var)
  File "/yt_dlp/utils.py", line 5348, in __get__
    return self.func(cls)
  File "/yt-dlp/yt_dlp/extractor/common.py", line 3649, in age_limit
    return max(traverse_obj(
TypeError: '>' not supported between instances of 'tuple' and 'int'
make: *** [yt_dlp/extractor/lazy_extractors.py] Error 1

**Comment by flashdagger** [comment]
As your problem is actually related to yt-dlp, I cannot answer it out of the box. Maybe you post your issue on their project.
